### ISSUE TITLE
Play OpenPipe samples

### ISSUE THREAD

**Issue by chonz0** [Tinwelint78/eBaghet#1]
Hi there! I've just found your project, congrats!

I was trying to play OpenPipe samples (it has asturian and galician bagpipes) using Mozzi, but I don't know how to do it.

Is there a chance you could help me with it?

Thanks in advance!
Gonzalo

**Comment by chonz0** [comment]
I have the SoundFont `.sf2` file with these samples, would you give me a hint of how to adapt these fo eBaghet? Thanks!

**Comment by Tinwelint78** [comment]
Hi Gonzalo!
I don't know about .sf2 file... But I have seen there are array of samples here:
https://github.com/openpipelabs/OpenPipeLibrary/tree/master/examples/E02_Samples
I think they can be adapted for eBaghet. If you like I can look into it later. Is the gaita fingering the same of GHB? on what notes are the drones tuned?

**Comment by chonz0** [comment]
Hey, thanks for your reply! Much appreciated :)
Yup, I've already seen the `E02_Samples` example and thought I could just replace the instrument data array as a drop in replacement, but I had no luck.

In the gaita, the fingering is different but I already did the correct mapping from sensor values to note. 
I'm currently being able to send a MIDI command through USB to my computer, as well as play the corresponding note, for each fingering position. But the thing is the sound played sounds awful haha, was looking to improve that.

Also, the it has only 1 drone, which it's tuned to C2

**Comment by Tinwelint78** [comment]
If you have an actual recording of a "base" note of the gaita chanter and one for the drone you can extract better quality samples with audacity. Here is how I have done it:
- open the sample audio file in audacity
- select the exact amount of samples. For example, if your file is sampled at 44100 Hz and the note played is an A4 (440 Hz), you have to select 44100/440 = 100 samples (circa....). Make also sure that start and end of selection are close to zero:
![immagine](https://user-images.githubusercontent.com/12066292/94000774-ed384b80-fd97-11ea-8fb0-231423c1aaaf.png)
here I have selected 95 samples because A4 on GHB is not 440 but a lot higher :)
- select Tools->Sample data export, insert correct sample number (100 in our example), select Linear measurement scale, select the output file, L channel first, then click "Ok"
![immagine](https://user-images.githubusercontent.com/12066292/94007109-3640cd80-fda1-11ea-823f-e4add1f48185.png)
- open the file with Excel or Calc, multiply the values by 127 to get the 8-bit values and by 32767 to get the 16-bit values
- copy each column (8-bit values and 16-bit values) into a text editor and substitute the line end charachters with a comma
- copy the resulting array into the corresponding array (f.ex. into ghb.h,  const int8_t __attribute__ ( ( section ( ".progmem.data" ) ) ) INST_DATA_GHB[] for 8-bit values and const int16_t __attribute__ ( ( section ( ".progmem.data" ) ) ) INST_DATA_GHB[]).
- modify INST_NUM_CELLS constant according to the sample number (100 in this case)
- repeat for the procedure for the drone sound
- modify the fingering table and the note ratio array
Let me know if you have any further question!

**Comment by Tinwelint78** [comment]
Or if you want and you have the samples I can create the new instruments :)

**Comment by chonz0** [comment]
Woah, you're truly awesome, thank you so much for the very well explained step-by-step.
Sure, I'll send you the [current bagpipe sample I have](https://file.io/9388N6sa4Ks4), I have very little spare time so if you can do that for me, it would be awesome, thanks buddy!

I've already asked the former owner of the (now abandoned) OpenPipe project if he could send me the rest of the samples, but I don't know if I'm gonna have luck with that.

I'm curious, but based on your project and replies, I asume you're more in the musical industry than in the software, amirite? 🔮

PS: if you prefer, you can reach me at `chonz0 [at] gmail [dot] com`
